"use client";

import { AnimatePresence, motion } from "framer-motion";
import { FileVideoCamera, FileText, Upload, X } from "lucide-react";
import { useCallback, useRef, useState, type ReactNode } from "react";

import { Button } from "@/components/ui/button";
import { formatBytes, formatDuration } from "@/lib/utils";
import type { MediaAsset } from "@/types/dashboard";

const VIDEO_ACCEPT = ".mp4,.mov,video/mp4,video/quicktime";
const TELEMETRY_ACCEPT = ".srt,.json,.log,application/json,text/plain";

export type IngestionDrawerProps = {
  open: boolean;
  onClose: () => void;
  video: MediaAsset | null;
  telemetry: MediaAsset | null;
  onVideoChange: (asset: MediaAsset | null) => void;
  onTelemetryChange: (asset: MediaAsset | null) => void;
  onStartReconstruction: () => void;
};

async function readVideoMeta(file: File): Promise<Pick<MediaAsset, "durationSec" | "previewUrl">> {
  const previewUrl = URL.createObjectURL(file);
  const durationSec = await new Promise<number>((resolve) => {
    const video = document.createElement("video");
    video.preload = "metadata";
    video.onloadedmetadata = () => resolve(video.duration || 0);
    video.onerror = () => resolve(0);
    video.src = previewUrl;
  });
  return { durationSec, previewUrl };
}

function toAsset(file: File, extra: Partial<MediaAsset> = {}): MediaAsset {
  return {
    file,
    name: file.name,
    size: file.size,
    ...extra,
  };
}

export function IngestionDrawer({
  open,
  onClose,
  video,
  telemetry,
  onVideoChange,
  onTelemetryChange,
  onStartReconstruction,
}: IngestionDrawerProps) {
  const ready = Boolean(video);

  return (
    <AnimatePresence>
      {open ? (
        <>
          <motion.button
            type="button"
            aria-label="Close ingestion drawer"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="absolute inset-0 z-[60] bg-black/40"
            onClick={onClose}
          />
          <motion.aside
            initial={{ x: 28, opacity: 0 }}
            animate={{ x: 0, opacity: 1 }}
            exit={{ x: 28, opacity: 0 }}
            transition={{ duration: 0.32, ease: [0.22, 1, 0.36, 1] }}
            className="glass-panel absolute top-4 right-4 bottom-4 z-[70] flex w-[min(100%-2rem,420px)] flex-col rounded-3xl p-5 shadow-2xl"
          >
            <div className="flex items-start justify-between">
              <div>
                <p className="hud-label">Ingest</p>
                <h2 className="mt-1 font-mono text-sm tracking-[0.16em] text-white uppercase">
                  New Drone Pass
                </h2>
              </div>
              <Button type="button" variant="ghost" size="icon" onClick={onClose} aria-label="Close">
                <X />
              </Button>
            </div>

            <p className="mt-3 text-xs leading-relaxed text-slate-400">
              Drop a single-pass video and its matching telemetry log. Reconstruction stays local
              until Phase 2 wires{" "}
              <code className="text-slate-300">POST /api/v1/upload</code>.
            </p>

            <div className="mt-5 flex flex-1 flex-col gap-3">
              <DropZone
                label="Drone Video"
                hint="Mandatory · MP4 / MOV · up to 4K"
                accept={VIDEO_ACCEPT}
                icon={<FileVideoCamera className="h-4 w-4 text-blue-400" />}
                asset={video}
                onFile={async (file) => {
                  const meta = await readVideoMeta(file);
                  onVideoChange(toAsset(file, meta));
                }}
                onClear={() => {
                  if (video?.previewUrl) URL.revokeObjectURL(video.previewUrl);
                  onVideoChange(null);
                }}
              />
              <DropZone
                label="Telemetry Log (.srt / .json) - OPTIONAL"
                hint="Optional · SRT / JSON / LOG"
                accept={TELEMETRY_ACCEPT}
                icon={<FileText className="h-4 w-4 text-emerald-400" />}
                asset={telemetry}
                onFile={(file) => onTelemetryChange(toAsset(file))}
                onClear={() => onTelemetryChange(null)}
              />
              <p className="mt-1 text-[10px] leading-relaxed text-slate-500">
                If omitted, synthetic GPS telemetry will be automatically generated by the engine.
              </p>
            </div>

            <Button
              type="button"
              className="mt-5 h-11 w-full rounded-2xl font-mono text-[11px] tracking-[0.2em] uppercase"
              disabled={!ready}
              onClick={onStartReconstruction}
            >
              Start 3D Reconstruction
            </Button>
          </motion.aside>
        </>
      ) : null}
    </AnimatePresence>
  );
}

type DropZoneProps = {
  label: string;
  hint: string;
  accept: string;
  icon: ReactNode;
  asset: MediaAsset | null;
  onFile: (file: File) => void | Promise<void>;
  onClear: () => void;
};

function DropZone({ label, hint, accept, icon, asset, onFile, onClear }: DropZoneProps) {
  const inputRef = useRef<HTMLInputElement>(null);
  const [over, setOver] = useState(false);

  const handleFiles = useCallback(
    (list: FileList | null) => {
      const file = list?.[0];
      if (file) void onFile(file);
    },
    [onFile],
  );

  return (
    <div
      onDragOver={(e) => {
        e.preventDefault();
        setOver(true);
      }}
      onDragLeave={() => setOver(false)}
      onDrop={(e) => {
        e.preventDefault();
        setOver(false);
        handleFiles(e.dataTransfer.files);
      }}
      className={`rounded-2xl border border-dashed p-4 transition-colors ${
        over ? "border-blue-400 bg-blue-500/10" : "border-slate-700 bg-slate-950/40"
      }`}
    >
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          {icon}
          <span className="text-xs font-medium text-slate-200">{label}</span>
        </div>
        {asset ? (
          <button
            type="button"
            onClick={onClear}
            className="text-[10px] tracking-widest text-slate-500 uppercase hover:text-white"
          >
            Clear
          </button>
        ) : null}
      </div>
      <p className="mt-1 text-[11px] text-slate-500">{hint}</p>

      {asset ? (
        <div className="mt-3 flex items-center justify-between rounded-xl border border-slate-800 bg-slate-900/80 px-3 py-2">
          <div className="min-w-0">
            <p className="truncate font-mono text-[11px] text-white">{asset.name}</p>
            <p className="mt-0.5 text-[10px] text-slate-500">
              {formatBytes(asset.size)}
              {asset.durationSec != null ? ` · ${formatDuration(asset.durationSec)}` : ""}
            </p>
          </div>
        </div>
      ) : (
        <button
          type="button"
          onClick={() => inputRef.current?.click()}
          className="mt-3 flex w-full items-center justify-center gap-2 rounded-xl py-6 text-xs text-slate-400 hover:text-white"
        >
          <Upload className="h-4 w-4" />
          Drop file or browse
        </button>
      )}

      <input
        ref={inputRef}
        type="file"
        accept={accept}
        className="hidden"
        onChange={(e) => {
          handleFiles(e.target.files);
          e.target.value = "";
        }}
      />
    </div>
  );
}
